Do not use dart_numerics
Turns out dart_numerics cannot run on the web because of a limitation of
javascript. So I searched the web for an algorithm for log base 10 and
found [this](https://math.stackexchange.com/a/1425065).

The error when compiling for the web using dart_numerics was:

 $ flutter build web
 Target dart2js failed: Exception:
 ../../../../.pub-cache/hosted/pub.dartlang.org/dart_numerics-0.0.5/lib/src/precision.dart:16:27:
 Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
 const int int64MaxValue = 9223372036854775807;
                           ^^^^^^^^^^^^^^^^^^^